---
## Written by santaricotta - github.com/santaricotta
## Licensed under AGPLv3.0 or later

- name: Uninstall and remove all traces of Kafka
  hosts: brokers
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  gather_facts: true

  vars:
    kafka_version: 4.0.0
    kafka_application_log_dir: /var/log/kafka
    kafka_message_log_dir: /srv/kafka
    kafka_firewalld_zone: public
    kafka_ports:
      - 9092/tcp
      - 9093/tcp

  tasks:
    - name: Stop kafka service
      ansible.builtin.systemd:
        name: kafka
        state: stopped
        enabled: false
      changed_when: false
      failed_when: false

    - name: Remove kafka service file
      ansible.builtin.file:
        path: /etc/systemd/system/kafka.service
        state: absent
      failed_when: false

    - name: Reload systemd to recognise changes
      ansible.builtin.systemd:
        daemon_reload: true
      changed_when: false

    - name: Remove kafka installation directory
      ansible.builtin.file:
        path: "/opt/kafka_2.13-{{ kafka_version }}"
        state: absent
      failed_when: false

    - name: "Remove {{ kafka_message_log_dir }} directory"
      ansible.builtin.file:
        path: "{{ kafka_message_log_dir }}"
        state: absent
      failed_when: false

    - name: "Remove {{ kafka_application_log_dir }} directory"
      ansible.builtin.file:
        path: "{{ kafka_application_log_dir }}"
        state: absent
      failed_when: false

    - name: Remove firewalld rules on RedHat systems
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Remove kafka ports from firewalld
          ansible.posix.firewalld:
            zone: "{{ kafka_firewalld_zone }}"
            port: "{{ item }}"
            state: disabled
            permanent: true
            immediate: true
          loop: "{{ kafka_ports }}"

        - name: Get current firewalld rules
          ansible.posix.firewalld_info:
            zones: "{{ kafka_firewalld_zone }}"
          register: firewalld_rules

        - name: Print current firewalld rules
          ansible.builtin.debug:
            var: firewalld_rules
